; convpng v7.3
; this file contains all the graphics for easier inclusion in a project
#include "bos_gfx.asm"
bos_gfx_transparent_color_index equ 255

#include "ico_appvar.asm" ; 258 bytes
#include "ico_asm.asm" ; 258 bytes
#include "ico_basic.asm" ; 258 bytes
#include "ico_bosbas.asm" ; 258 bytes
#include "ico_c.asm" ; 258 bytes
#include "ico_cursor.asm" ; 258 bytes
#include "ico_data.asm" ; 258 bytes
#include "ico_folder.asm" ; 258 bytes
#include "ico_ice.asm" ; 258 bytes
#include "ico_link.asm" ; 258 bytes
#include "ico_locked_prgm.asm" ; 258 bytes
#include "ico_prgm.asm" ; 258 bytes
#include "ico_text.asm" ; 258 bytes
#include "ico_xani.asm" ; 258 bytes
#include "ico_ximg.asm" ; 258 bytes

